### ISSUE TITLE
Change app ID?

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/FP1-Launcher#1]
The current app ID is `org.fairphone.launcher`. Should we change it to `community.fairphone.launcher`?

**Comment by Roboe** [comment]
Sure. I think arguments for the FP2 apps apply here too (douwe at [Fairphone Forum](https://forum.fairphone.com/t/publishing-fairphone-specific-apps-launcher-contact-widget-on-f-droid/28008/50?u=roboe)):
> Hey all, one thing we noticed here at Fairphone: the package name of the app can not be the same as the original package for two reasons:
>
>  - it will cause a conflict with the signature of our version of the app and the installation might fail.
>  - people might get confused about the creator of these apps. So referencing Fairphone as the origin of this code is fine, but it should be clear it is a community (WeAreFairphone) project now.
>
> Keep on pushing!

(from https://github.com/WeAreFairphone/android_packages_apps_MyContactsWidget/issues/4)

**Comment by z3ntu** [comment]
Will fix this after #2

**Comment by Roboe** [comment]
Just reminding that directories should be changed too from `org/fairphone/launcher/` to `community/fairphone/launcher/`.

**Comment by Rudloff** [comment]
Is this really necessary? I see the FP2 launcher still uses `src/com/fairphone/fplauncher3`.

**Comment by z3ntu** [comment]
I did it in the other repos, but didn't touch the FP2 launcher repo yet.

**Comment by Roboe** [comment]
As @z3ntu said, the FP2 launcher has the `community.fairphone.fplauncher3` package name with a minimal `build.gradle` patch: https://github.com/WeAreFairphone/FP2-Launcher/commit/cb97eaed1c233ac7623ff05b131df6ba0c6dd696

**Comment by Roboe** [comment]
Also, following our other apps, we increase `versionCode` and bump `versionName` to `2.0` after the package change is applied.
