### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/FP1-Launcher#5]
@Roboe @z3ntu Do you want to make some other changes or can I tag a 2.0 release?

**Comment by Roboe** [comment]
Metadata? I think we should differentiate this enough from the Fairphone 2 launcher from the beginning. It seems difficult, though. How about naming it "Fairphone [First Edition](https://de.wikipedia.org/wiki/Fairphone_First_Edition) Launcher"? Or just "Fairphone 1 Launcher", but I don't really like it&hellip; **Edit:** #6 

Also, the name of the app is "Fairphone OS", which doesn't seem correct (it's just a third-party launcher now). **Edit:** #7

**Comment by Rudloff** [comment]
@Roboe Now that #6 and #7 are merged, do you see anything else we need to do before tagging a release?

**Comment by Roboe** [comment]
Go ahead before my perfectionism can come up with something! :joy:

**Comment by Rudloff** [comment]
I tagged the release. I will also try to update the (very old) F-Droid build recipe.

**Comment by Roboe** [comment]
Mind that the appid changed to `community.fairphone.launcher`

**Comment by Rudloff** [comment]
The F-Droid merge request is here: https://gitlab.com/fdroid/fdroiddata/merge_requests/3281
