### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by benzntech** [WeAreFairphone/FP1-Launcher#8]
Not able to install Application on redmi note 5 pro.
Error ScreenShot.
![372ea324-8597-4642-831e-65bd1d88ee76](https://user-images.githubusercontent.com/4044180/42360655-b9dd4330-8107-11e8-834d-cac038894545.jpeg)
About the device.
![299a3612-659a-4478-93a5-c476a3b43e74](https://user-images.githubusercontent.com/4044180/42360661-c401c8ea-8107-11e8-9d3f-45c33682723c.jpeg)

**Comment by z3ntu** [comment]
Can you put the apk in your PC and try to install it with adb : `adb install filename.apk`

**Comment by Roboe** [comment]
As @z3ntu implies, we need the exact error to tackle this issue. The command above will show it.

You can [get the APK right from the F-Droid site](https://f-droid.org/es/packages/community.fairphone.launcher/) and install ADB [for Windows](https://forum.xda-developers.com/showthread.php?t=2317790), Linux (from your software repos, install the `adb` or `android-platform-tools` packages) or [Mac](https://stackoverflow.com/questions/31374085/installing-adb-on-mac-os-x#32314718).

**Comment by benzntech** [comment]
As @z3ntu @Roboe Instructed :- After install it with adb
adb install community.fairphone.launcher_2.apk 
Failed to install community.fairphone.launcher_2.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package community.fairphone.launcher attempting to redeclare permission com.android.launcher.permission.WRITE_SETTINGS already owned by com.miui.home]
![screenshot from 2018-07-08 00-38-23](https://user-images.githubusercontent.com/4044180/42413883-4a6cd27c-8247-11e8-8298-1290b87e6f52.png)

**Comment by Rudloff** [comment]
This looks a lot like https://github.com/WeAreFairphone/FP2-Launcher/issues/6.

**Comment by Roboe** [comment]
In fact, it's the same issue, but this time with launchers forked off Launcher2 instead of Launcher3.

Could you fix this and release a hotfix to F-Droid, @Rudloff? Removing the `com.android.launcher` prefix should be sufficient, like we did in https://github.com/WeAreFairphone/FP2-Launcher/commit/dc8a6cb47695b6f5bbd18598c90db3dfa4f6dd48
